### ISSUE TITLE
minimal steps to point api-cardano-db-hasura to an existing relay?

### ISSUE THREAD

**Issue by bitnado-io** [input-output-hk/cardano-graphql#277]
it looks like the docker-compose stitches together multiple services including an existing cardano-node instance but we're just trying to run the graphql api and point it to our relay

i see this in the readme:

> Should you wish to have more control over the server, or stitch the schema with an existing service, consider importing the executable schema from the @cardano-graphql/api-* packages only

to use `api-cardano-db-hasura` do we also need `cardano-db-sync-extended` and `hasura`? is there a minimal example stitching the graphql api to an existing service that i could be referred to?

any help would be greatly appreciated thanks!

**Comment by rhyslbw** [comment]
> we're just trying to run the graphql api and point it to our relay

You can simply omit the `cardano-node` service from the compose file, and mount the relay's socket into the `cardano-db-sync` container via a host mount:

``` yaml
version: "3.5"

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-11.5-alpine}
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    shm_size: '2gb'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  cardano-db-sync-extended:
    image: inputoutput/cardano-db-sync:${CARDANO_DB_SYNC_VERSION:-3.1.0}
    command: [
      "--config", "/config/config.json",
      "--socket-path", "/node.socket"
    ]
    environment:
      - EXTENDED=true
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - cardano-node
      - postgres
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - ./config/network/${NETWORK:-mainnet}/cardano-db-sync:/config
      - ./config/network/${NETWORK:-mainnet}/genesis:/genesis
      - ./path/to/node.socket:/node.socket
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
...
```
