### ISSUE TITLE
PROMETHEUS_METRICS Usage

### ISSUE THREAD

**Issue by CyberCyclone** [input-output-hk/cardano-graphql#663]
I'm trying to active Prometheus on cardano-graphql. I've added the PROMETHEUS_METRICS=true env to the cardano-graphql section in docker-compose.

```
cardano-graphql:
    build:
      args:
        - NETWORK=${NETWORK:-mainnet}
        - METADATA_SERVER_URI=${METADATA_SERVER_URI:-https://tokens.cardano.org}
      cache_from: [ inputoutput/cardano-graphql:latest ]
      context: .
      target: server
    image: inputoutput/cardano-graphql:${CARDANO_GRAPHQL_VERSION:-6.1.0}-${NETWORK:-mainnet}
    environment:
      - ALLOW_INTROSPECTION=true
      - CACHE_ENABLED=true
      - LOGGER_MIN_SEVERITY=${LOGGER_MIN_SEVERITY:-info}
      - PROMETHEUS_METRICS=true
    expose:
      - ${API_PORT:-3100}
    ports:
      - ${API_PORT:-3100}:3100
    restart: on-failure
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
```

It starts up fine according to Docker, however the endpoint on port 3101 (on testnet) fails immediately, both with `/` and `/metrics` paths.

Is PROMETHEUS_METRICS still a valid option?

Thanks!

**Comment by rhyslbw** [comment]
You have to also set `TRACING=true`, otherwise it will fail with:
```
{"name":"cardano-graphql","hostname":"rhys-desktop","pid":81485,"level":50,"msg":"Tracing is required for Prometheus metrics","time":"2022-01-26T13:16:08.623Z","v":0}
```

I've just updated the [wiki](https://github.com/input-output-hk/cardano-graphql/wiki/Configuration#prometheus_metricstrue) to detail this

**Comment by Robinyo** [comment]
-> I'm trying to add support for Prometheus (and Grafana) to cardano-graphql. 

Me too :)

docker-compose.xml:

```
version: "3.8"

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-11.5-alpine}
    restart: on-failure
    container_name: postgres
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    shm_size: '2gb'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        
  cardano-node-ogmios:
    image: cardanosolutions/cardano-node-ogmios:${CARDANO_NODE_OGMIOS_VERSION:-v5.1.0}-${NETWORK:-mainnet}
    restart: on-failure
    container_name: cardano-node-ogmios
    ports:
      - ${OGMIOS_PORT:-1337}:1337
    volumes:
      - node-db:/db
      - node-ipc:/ipc
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"

  cardano-db-sync-extended:
    image: inputoutput/cardano-db-sync:${CARDANO_DB_SYNC_VERSION:-12.0.0}
    command: [
      "--config", "/config/cardano-db-sync/config.json",
      "--socket-path", "/node-ipc/node.socket"
    ]
    restart: on-failure
    container_name: cardano-db-sync-extended
    environment:
      - EXTENDED=true
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - RESTORE_SNAPSHOT=${RESTORE_SNAPSHOT:-}
      - RESTORE_RECREATE_DB=N
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - ./config/network/${NETWORK:-mainnet}:/config
      - db-sync-data:/var/lib/cdbsync
      - node-ipc:/node-ipc
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    depends_on:
      - cardano-node-ogmios
      - postgres

  hasura:
    image: inputoutput/cardano-graphql-hasura:${CARDANO_GRAPHQL_VERSION:-6.2.0}
    restart: on-failure
    container_name: hasura
    ports:
      - ${HASURA_PORT:-8090}:8080
    environment:
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_CORS_DOMAIN=http://localhost:9695
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    depends_on:
      - "postgres"

  cardano-graphql:
    image: inputoutput/cardano-graphql:${CARDANO_GRAPHQL_VERSION:-6.2.0}-${NETWORK:-mainnet}
    restart: on-failure
    container_name: cardano-graphql
    environment:
      - ALLOW_INTROSPECTION=true
      - CACHE_ENABLED=true
      - LOGGER_MIN_SEVERITY=${LOGGER_MIN_SEVERITY:-info}
      - PROMETHEUS_METRICS=true
      - TRACING=true
    expose:
      - ${API_PORT:-3100}
    ports:
      - ${API_PORT:-3100}:3100
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  prometheus:
    image: prom/prometheus:latest
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    container_name: prometheus
    ports:
      - ${PROMETHEUS_PORT:-9090}:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/var/lib/prometheus/data

secrets:
  postgres_db:
    file: ./placeholder-secrets/postgres_db
  postgres_password:
    file: ./placeholder-secrets/postgres_password
  postgres_user:
    file: ./placeholder-secrets/postgres_user

volumes:
  db-sync-data:
  node-db:
  node-ipc:
  postgres-data:
  prometheus-data:
```

Run script:

```
export NETWORK=testnet && \
export POSTGRES_VERSION=11.5-alpine && \
export CARDANO_NODE_OGMIOS_VERSION=v5.1.0 && \
export CARDANO_DB_SYNC_VERSION=12.0.0 && \
export CARDANO_GRAPHQL_VERSION=6.2.0 && \
docker pull inputoutput/cardano-graphql:${CARDANO_GRAPHQL_VERSION}-${NETWORK} && \
docker pull inputoutput/cardano-graphql-hasura:${CARDANO_GRAPHQL_VERSION} && \
docker pull cardanosolutions/cardano-node-ogmios:${CARDANO_NODE_OGMIOS_VERSION}-${NETWORK} && \
export RESTORE_SNAPSHOT=https://updates-cardano-testnet.s3.amazonaws.com/cardano-db-sync/12/db-sync-snapshot-schema-12-block-3298999-x86_64.tgz  && \
export API_PORT=3101 && \
export HASURA_PORT=8091 && \
export OGMIOS_PORT=1338 && \
export POSTGRES_PORT=5433 && \
export PROMETHEUS_PORT=9090 && \
docker-compose -p ${NETWORK} up -d
```

View logs:

```
docker container logs postgres
docker container logs cardano-node-ogmios
docker container logs cardano-db-sync-extended
docker container logs hasura
docker container logs cardano-graphql
```

prometheus.yml:

```
global:
  scrape_interval: 15s
  scrape_timeout: 5s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'cardano-graphql:3101'
```

alerts.yml:

```
groups:
  - name: DemoAlerts
    rules:
      - alert: InstanceDown
        expr: up{job="services"} < 1
        for: 5m
```

Navigate to http://localhost:9090/targets

![Screen Shot 2022-02-15 at 11 43 32](https://user-images.githubusercontent.com/12203540/153971066-ba118c23-7e54-4fcf-8975-e05ec2fcee80.png)
