### ISSUE TITLE
Pull and Run via Docker Compose

### ISSUE THREAD

**Issue by Robinyo** [input-output-hk/cardano-graphql#671]
The project [README.md](https://github.com/input-output-hk/cardano-graphql#readme) in the section **Pull and Run via Docker Compose** refers to a cardano-graphql image and a cardano-graphql-hasura image with **6.2.0** in the tag.

On DockerHub I could not find a cardano-graphql image or a cardano-graphql-hasura image with **6.2.0** in the tag:

![Screen Shot 2022-02-07 at 12 11 13](https://user-images.githubusercontent.com/12203540/152710291-4b03f8b9-f56a-42a9-b70a-b17c65c9866e.png)

The sample [docker-compose.yml](https://github.com/input-output-hk/cardano-graphql/blob/master/docker-compose.yml) file also refers to **6.2.0**:

```
  hasura:
    image: inputoutput/cardano-graphql-hasura:${CARDANO_GRAPHQL_VERSION:-6.2.0}

  ...

  cardano-graphql:
    image: inputoutput/cardano-graphql:${CARDANO_GRAPHQL_VERSION:-6.2.0}-${NETWORK:-mainnet}
```

Should I use the **6.1.0** images?
