### ISSUE TITLE
cardano-graphql schema migrations failing for private testnet

### ISSUE THREAD

**Issue by jonathangenlambda** [input-output-hk/cardano-graphql#711]
### Summary

We have a private testnet up and running, with cardano-node (v1.34.1), cardano-ogmios, postgres and cardano-db-sync successfully connected and everything works fine.

Now we want to bring in cardano-graphql but we seem not to get it working. Here is the docker-compose.yml (note that we have to use cardano-db-sync:master otherwise cardano-db-sync would fail to sync with the private testnet which bootstraps into alonzo from block 0):

```
version: "3.3"

services:
  testnet:
    build:
      context: .
    ports:
      - "3001:3001"
      - "12789:12789"
    volumes:
      - ${PWD}/shared/configs:/testnet/configs
      - ${PWD}/shared/sockets:/testnet/sockets
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cardano-ogmios:
      command: [
        "--host", "0.0.0.0",
        "--node-socket", "/shared/sockets/node-pool1.sock",
        "--node-config", "/shared/configs/configuration.yaml",
      ]
      image: cardanosolutions/ogmios:v5.2.0
      depends_on:
        - testnet
      logging:
        driver: "json-file"
        options:
          max-size: "400k"
          max-file: "20"
      ports:
        - ${OGMIOS_PORT:-1337}:1337
      restart: on-failure
      volumes:
        - ${PWD}/shared:/shared

  postgres:
    image: postgres:11.5-alpine
    shm_size: 1g 
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cardano-db-sync:
    image: inputoutput/cardano-db-sync:master
    command: [
      "--config /shared/configs/db-sync-config.yaml",
      "--socket-path /shared/sockets/node-pool1.sock"
    ]
    environment:
      - EXTENDED=true
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
      - RESTORE_RECREATE_DB=N
    depends_on:
      - testnet
      - postgres
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - ${PWD}/shared:/shared
      # NOTE: uncomment if you want to keep data
      # - ${PWD}/dbdata/sync/db-sync-data:/var/lib/cdbsync
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  hasura:
    image: inputoutput/cardano-graphql-hasura:master
    ports:
      - ${HASURA_PORT:-8090}:8080
    depends_on:
      - "postgres"
    restart: on-failure
    environment:
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_CORS_DOMAIN=http://localhost:9695
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

secrets: 
  postgres_db:
    file: ./db/postgres_db
  postgres_password:
    file: ./db/postgres_password
  postgres_user:
    file: ./db/postgres_user

volumes:
  db-sync-data:
  postgres:
  prometheus-data:
```

When all services are up and running and the socket files of the private testnet nodes are exposed, we are firing up cardano-graphql with another docker-compose:

```
version: "3.3"

services:
  cardano-graphql:
    image: inputoutput/cardano-graphql:master
    environment:
      - CARDANO_NODE_CONFIG_PATH=/shared/configs/configuration-json.json
      - CARDANO_NODE_SOCKET_PATH=/shared/sockets/node-pool1.sock
      - HASURA_URI=http://hasura:8080
      - OGMIOS_HOST=cardano-ogmios
      - OGMIOS_PORT=1337
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - ALLOW_INTROSPECTION=true
      - CACHE_ENABLED=true
      - LOGGER_MIN_SEVERITY=${LOGGER_MIN_SEVERITY:-debug}
    expose:
      - ${API_PORT:-3100}
    ports:
      - ${API_PORT:-3100}:3100
    restart: on-failure
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    volumes:
      - ${PWD}/shared:/shared
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

secrets: 
  postgres_db:
    file: ./db/postgres_db
  postgres_password:
    file: ./db/postgres_password
  postgres_user:
    file: ./db/postgres_user

volumes:
  db-sync-data:
  postgres:
  prometheus-data:
```

When cardano-graphql starts we see the following output:

```
{"name":"cardano-graphql","hostname":"8c1a9ab21496","pid":1,"level":20,"module":"Db","msg":"pgSubscriber: Connected","time":"2022-05-16T17:34:47.695Z","v":0}
{"name":"cardano-graphql","hostname":"8c1a9ab21496","pid":1,"level":30,"module":"Server","msg":"Initializing","time":"2022-05-16T17:34:47.696Z","v":0}
{"name":"cardano-graphql","hostname":"8c1a9ab21496","pid":1,"level":30,"module":"HasuraClient","msg":"Initializing","time":"2022-05-16T17:34:47.811Z","v":0}
{"name":"cardano-graphql","hostname":"8c1a9ab21496","pid":1,"level":20,"module":"HasuraClient","msg":"{\"level\":\"info\",\"msg\":\"Help us improve Hasura! The cli collects anonymized usage stats which\\nallow us to keep improving Hasura at warp speed. To opt-out or read more,\\nvisit https://hasura.io/docs/1.0/graphql/manual/guides/telemetry.html\\n\",\"time\":\"2022-05-16T17:34:47Z\"}\n{\"level\":\"info\",\"msg\":\"Applying migrations...\",\"time\":\"2022-05-16T17:34:50Z\"}\n{\"level\":\"info\",\"msg\":\"nothing to apply\",\"time\":\"2022-05-16T17:34:50Z\"}\n","time":"2022-05-16T17:34:50.114Z","v":0}
{"name":"cardano-graphql","hostname":"8c1a9ab21496","pid":1,"level":20,"module":"HasuraClient","msg":"{\"level\":\"info\",\"msg\":\"Applying migrations...\",\"time\":\"2022-05-16T17:34:50Z\"}\n","time":"2022-05-16T17:34:50.250Z","v":0}
{"name":"cardano-graphql","hostname":"8c1a9ab21496","pid":1,"level":20,"msg":"Applying PostgreSQL schema migrations: Attempt 1 of 10, retrying...","time":"2022-05-16T17:34:50.250Z","v":0}
{"name":"cardano-graphql","hostname":"8c1a9ab21496","pid":1,"level":20,"module":"HasuraClient","msg":"{\"level\":\"info\",\"msg\":\"Applying migrations...\",\"time\":\"2022-05-16T17:34:51Z\"}\n{\"level\":\"info\",\"msg\":\"nothing to apply\",\"time\":\"2022-05-16T17:34:51Z\"}\n","time":"2022-05-16T17:34:51.353Z","v":0}
{"name":"cardano-graphql","hostname":"8c1a9ab21496","pid":1,"level":20,"module":"HasuraClient","msg":"{\"level\":\"info\",\"msg\":\"Applying migrations...\",\"time\":\"2022-05-16T17:34:51Z\"}\n","time":"2022-05-16T17:34:51.488Z","v":0}
```

This continues until Attempt 10 of 10 followed by a final error output:

```
{"name":"cardano-graphql","hostname":"8c1a9ab21496","pid":1,"level":50,"msg":"Command failed: /usr/local/bin/hasura --skip-update-check --project /app/packages/api-cardano-db-hasura/hasura/project --endpoint http://hasura:8080 migrate apply --up all\ntime=\"2022-05-16T17:38:16Z\" level=fatal msg=\"apply failed: [postgres-error] query execution failed ($.args[0].args)\\r\\nFile: '1589369664961_init/up.sql'\\r\\n{\\n    \\\"check_metadata_consistency\\\": false,
...
FatalError: column pool.reward_addr does not exist\\r\\nHint: Perhaps you meant to reference the column \\\"pool.reward_addr_id\\\".\"\n","time":"2022-05-16T17:38:16.334Z","v":0}
```

### Actual Result

See summary description.

### Expected Result

Expected is that cardano-graphql gets up and running without errors and that we can connect to it through http://localhost:3100/graphql.

### Environment

Using environment as specified in the docker-compose in the Summary.

### Platform

- [X] Linux (Ubuntu)
- [ ] Linux (Other)
- [ ] macOS
- [ ] Windows

### Platform version

Ubuntu 22.04

### Runtime

- [ ] Node.js
- [ ] Docker
