### ISSUE TITLE
Authentication failed with Postgres - Connection failed

### ISSUE THREAD

**Issue by air3ijai** [input-output-hk/cardano-graphql#712]
### Summary

When we specify DB connection parameters via files we got an error about failed connection.

If we put data from files into environment variables it started to work as expected.

### Steps to reproduce the bug

1. Create files with connection parameters
    ```
   echo "cardano" > ./config/secrets/postgres_db
   echo "cardano" > ./config/secrets/postgres_user
   echo `openssl rand -base64 30` > ./config/secrets/postgres_password
2. Start `node`, `postgres` and `db-sync` and point them to created files
3. Use the following configuration for cardano-graphql container:
```yaml
  cardano-graphql:
    container_name: graphql
    image: inputoutput/cardano-graphql:${CARDANO_GRAPHQL_VERSION:-6.2.0}-${NETWORK:-mainnet}
    environment:
      - ALLOW_INTROSPECTION=true
      - CACHE_ENABLED=true
      - LOGGER_MIN_SEVERITY=${LOGGER_MIN_SEVERITY:-info}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      # - POSTGRES_DB=cardano
      # - POSTGRES_USER=cardano
      # - POSTGRES_PASSWORD=ra8TaKb0XPACvkXBojgg70KPPELX2twc9UjsbEZl
    expose:
      - ${API_PORT:-3100}
    ports:
      - ${API_PORT:-3100}:3100
    restart: on-failure
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
```

### Actual Result

We got messages about connection errors
```
postgres  | 2022-05-24 16:22:09.827 UTC [26] FATAL:  password authentication failed for user "cardano
postgres  |     "
postgres  | 2022-05-24 16:22:09.827 UTC [26] DETAIL:  Role "cardano
postgres  |     " does not exist.
postgres  |     Connection matched pg_hba.conf line 95: "host all all all md5"
graphql   | {"name":"cardano-graphql","hostname":"04d8649e5bd8","pid":1,"level":50,"err":{"length":104,"name":"error","severity":"FATAL","code":"28P01","file":"auth.c","line":"336","routine":"auth_failed"},"msg":"password authentication failed for user \"cardano\n\"","time":"2022-05-24T16:22:09.829Z","v":0}
graphql   | {"name":"cardano-graphql","hostname":"04d8649e5bd8","pid":1,"level":40,"module":"Db","msg":"pgSubscriber: Reconnecting attempt 1","time":"2022-05-24T16:22:09.832Z","v":0}
postgres  | 2022-05-24 16:22:09.835 UTC [27] FATAL:  password authentication failed for user "cardano
postgres  |     "
postgres  | 2022-05-24 16:22:09.835 UTC [27] DETAIL:  Role "cardano
postgres  |     " does not exist.
postgres  |     Connection matched pg_hba.conf line 95: "host all all all md5"
```
```
graphql   | {"name":"cardano-graphql","hostname":"acf8a073c53a","pid":1,"level":40,"module":"Db","msg":"pgSubscriber: Reconnecting attempt 3","time":"2022-05-24T16:42:21.810Z","v":0}
postgres  | 2022-05-24 16:42:21.812 UTC [31] FATAL:  password authentication failed for user "cardano"
postgres  | 2022-05-24 16:42:21.812 UTC [31] DETAIL:  Password does not match for user "cardano".
postgres  |     Connection matched pg_hba.conf line 95: "host all all all md5"
```

Suspicious part is the following
```
postgres  | 2022-05-24 16:22:09.827 UTC [26] DETAIL:  Role "cardano
postgres  |     " does not exist.

user \"cardano\n\"
```
And looks like it can be related to the new line.

### Expected Result

We should be able to specify DB connection parameters via files and they should work correctly.

Same files are used for db-sync an it works as expected.

### Environment

Connection parameters files
```bash
[root@cardano]# cat config/secrets/postgres_*
cardano
ra8TaKb0XPACvkXBojgg70KPPELX2twc9UjsbEZl
cardano
```

### Platform

- [X] Linux (Ubuntu)
- [ ] Linux (Other)
- [ ] macOS
- [ ] Windows

### Runtime

- [ ] Node.js
- [X] Docker

### Runtime version

Docker version 20.10.13, build a224086
