### ISSUE TITLE
Issue with wiki documentation (mentions deprecated? cardano-db-sync-extended)

### ISSUE THREAD

**Issue by Jack-0** [input-output-hk/cardano-graphql#739]
### Summary

As a developer trying to experiment with graphql I came across this misleading documentation.

https://github.com/input-output-hk/cardano-graphql/wiki 
```
The data returned by this API is sourced from a PostgreSQL database produced by [cardano-db-sync-extended](https://github.com/input-output-hk/cardano-db-sync/tree/master/cardano-db-sync-extended)
```

The cardano-db-sync-extend url is missing and I believe this is deprected by standalone cardano-db-sync?

### Steps to reproduce the bug

1. go to https://github.com/input-output-hk/cardano-graphql/wiki 
2. read the first line

### Actual Result

Invalid documentation mentioning deprecated cardano-db-sync-extended 

### Expected Result

Valid documentation mentioning deprecated cardano-db-sync

### Environment

https://github.com/input-output-hk/cardano-graphql/wiki

### Platform

- [X] Linux (Ubuntu)
- [X] Linux (Other)
- [X] macOS
- [X] Windows

### Platform version

n/a

### Runtime

- [X] Node.js
- [X] Docker

### Runtime version

n/a

**Comment by thatsbrandon** [comment]
I ran into this issue as well, super confusing. You have to use the `inputoutput/cardano-db-sync:13.0.0` image & add `EXTENDED` as a environment variable & set it to `true`.

```yaml
//  Kubernetes pod
image: inputoutput/cardano-db-sync:13.0.0
          name: ocs-cardano-testnet-db-sync
          env:
            - name: NETWORK
              value: testnet
            - name: EXTENDED
              value: "true"
```
