### ISSUE TITLE
Cardano-graphql has issue connecting to cardano-node

### ISSUE THREAD

**Issue by thatsbrandon** [input-output-hk/cardano-graphql#744]
### Ask a question

I keep getting this logs on my kubernetes graphql pod, it appears to me the cardano-graphql is having trouble connecting to the `cardano-node`. Only issue is I can't find anywhere on the docs how that connection is being handled? Is it through a virtual network like docker container use in a stack or does it use `node-ipc/node.socket` file. I have `cardano-graphql` in a different pod.

POD TOPOLOGY
Pod 1
-----------------------------------
| CARDANO-NODE         
| CARDANO-DB-SYNC   
| CARDANO-OGMIOS    
-----------------------------------

Pod 2
-----------------------------------
| CARDANO-GRAPHQL
| CARDANO-HASURA        
-----------------------------------
NOTE: I setup my pods this way to split up the workloads; The first pod has components that are super close to the node and rely on the `node.socket` file.

Pod.yml
```yml
env:
            - name: NETWORK
              value: testnet
            - name: METADATA_SERVER_URI
              value: "https://tokens.cardano.org"
            - name: ALLOW_INTROSPECTION
              value: "true"
            - name: CACHE_ENABLED
              value: "true"
            - name: LOGGER_MIN_SEVERITY
              value: debug
            - name: API_PORT
              value: "3100"
            - name: OGMIOS_HOST
              value: "cardano-ogmios-testnet-service"
            - name: OGMIOS_PORT
              value: "1337"
            - name: HASURA_URI
              value: "http://cardano-hasura-server-service:8080"
            - name: LISTEN_ADDRESS
              value: "0.0.0.0"
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-chaindb-config
                  key: ocs-postgres-chaindb-url
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-chaindb-secrets
                  key: postgres_db
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-chaindb-secrets
                  key: postgres_password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-chaindb-secrets
                  key: postgres_user

```

The logs are the following
```console
{"name":"cardano-graphql","hostname":"ocs-cardano-graphql-testnet-d875c874-fzr2x","pid":1,"level":20,"module":"DataFetcher","instance":"ServerHealth","msg":"value fetched after 30 seconds","time":"2022-07-29T03:24:04.793Z","v":0}
{"name":"cardano-graphql","hostname":"ocs-cardano-graphql-testnet-d875c874-fzr2x","pid":1,"level":20,"module":"DataFetcher","instance":"ServerHealth","msg":"Initial value fetched","time":"2022-07-29T03:24:05.393Z","v":0}
{"name":"cardano-graphql","hostname":"ocs-cardano-graphql-testnet-d875c874-fzr2x","pid":1,"level":20,"msg":"Establishing connection to cardano-node: Attempt 34 of 101, retrying...","time":"2022-07-29T03:24:05.397Z","v":0}
.............. ( repeats over X100s )
```
These logs repeat hundreds of time, it appears port `3100` isn't even being started through graphql at my pods current state.

Does anyone have a clue on how I can get my graphql server to connect?
